# In this notebook we are going to cover the fundamental concepts of tensors using tensorflow

## Introduction to tensors

### Creating tensors with tf.constant

In [2]:
# Imports
import tensorflow as tf
print(tf.__version__)

2.6.0


In [3]:
# Creating tensors with tf.constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# check the number of dimensions of the tensors
scalar.ndim

0

In [5]:
# create a vector
vector = tf.constant([10,10.36])
vector

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.  , 10.36], dtype=float32)>

In [6]:
vector.ndim

1

In [7]:
# create a matrix 
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
# create another matrix
matrix = tf.constant([[1.,2.,4.],
                      [10.,13.,7.],
                      [14.,2.,15]], dtype=tf.float16)
matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[ 1.,  2.,  4.],
       [10., 13.,  7.],
       [14.,  2., 15.]], dtype=float16)>

In [10]:
matrix.ndim

2

In [11]:
# another matrix
matrix = tf.constant([[[1,2,4],[1,2,3]],[[1,2,4],[1,2,3]]])
matrix

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 4],
        [1, 2, 3]],

       [[1, 2, 4],
        [1, 2, 3]]], dtype=int32)>

In [12]:
matrix.ndim

3

In [13]:
# another matrix
matrix = tf.constant([
                      [
                       [
                       [1,2,4],
                       [1,2,3]
                       ],
                       [
                       [1,2,4],
                       [1,2,3]
                       ]
                      ],
                      [[
                       [1,2,4],
                       [1,2,3]
                       ],
                      [
                       [1,2,4],
                       [1,2,3]
                       ]
                      ]
                    ])
matrix

<tf.Tensor: shape=(2, 2, 2, 3), dtype=int32, numpy=
array([[[[1, 2, 4],
         [1, 2, 3]],

        [[1, 2, 4],
         [1, 2, 3]]],


       [[[1, 2, 4],
         [1, 2, 3]],

        [[1, 2, 4],
         [1, 2, 3]]]], dtype=int32)>

In [14]:
matrix.ndim

4

### Creating tensors with tf.Variable

In [15]:
changeable_tensor = tf.Variable([10])
changeable_tensor

<tf.Variable 'Variable:0' shape=(1,) dtype=int32, numpy=array([10], dtype=int32)>

In [16]:
changeable_tensor[0].assign(8)

<tf.Variable 'UnreadVariable' shape=(1,) dtype=int32, numpy=array([8], dtype=int32)>

In [17]:
changeable_tensor = 7
changeable_tensor

7

In [18]:
changeable_tensor[0].assign(8)

TypeError: ignored

### Creating random tensors with tf.random

**Note**: Useful when the NN weights are initialized

In [19]:
random_1 = tf.random.Generator.from_seed(75)
random_1 = random_1.normal((3,3))
random_1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.06093803, -0.99516404,  0.7279114 ],
       [ 1.3452564 ,  0.89255804,  0.54797494],
       [-0.9483233 , -0.14723077, -0.3514068 ]], dtype=float32)>

### Shuffle the order of elements in a tensor

**Note**: Useful to shuffle the order 

In [20]:
tf.random.shuffle(random_1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.9483233 , -0.14723077, -0.3514068 ],
       [ 1.3452564 ,  0.89255804,  0.54797494],
       [-0.06093803, -0.99516404,  0.7279114 ]], dtype=float32)>

### Tensor attributes

In [21]:
ones = tf.ones(shape=(3,2,3,4))

In [22]:
ones

<tf.Tensor: shape=(3, 2, 3, 4), dtype=float32, numpy=
array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]], dtype=float32)>

In [23]:
tf.size(ones)

<tf.Tensor: shape=(), dtype=int32, numpy=72>

In [24]:
ones.ndim

4

In [25]:
ones.shape

TensorShape([3, 2, 3, 4])

### Indexing and expanding of tensors

In [26]:
# get the first 2 elements of each dimension
ones[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [27]:
# get the last item of each row of a rank 2 tensor
rank_2_tensor = tf.constant([[10,7],[1,2]])
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 2], dtype=int32)>

In [28]:
# Adding extra dimensions to our tensor
rank_2_tensor[...,tf.newaxis]

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 1],
        [ 2]]], dtype=int32)>

In [29]:
rank_2_tensor[:,:,tf.newaxis]

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 1],
        [ 2]]], dtype=int32)>

### Manipulating tensors

In [33]:
# Basic operations like +, -, *, /

In [30]:
tensor = tf.constant([[10,3],[1,7]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  3],
       [ 1,  7]], dtype=int32)>

In [31]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 13],
       [11, 17]], dtype=int32)>

In [34]:
tf.add(tensor, tf.multiply(tensor,10))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[110,  33],
       [ 11,  77]], dtype=int32)>

### Matrix mulitplication

In [35]:
tensor_2 = tf.constant([[12,1],[12,1]])
tf.linalg.matmul(tensor,tensor_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[156,  13],
       [ 96,   8]], dtype=int32)>

### Chance the DataType of a Tensor
**default: int32**

In [37]:
tensor_casted = tf.cast(tensor,dtype=tf.int16)

### Aggregation of tensors

In [44]:
tensor = tf.constant([[-10,3],[-15,3]])

In [45]:
tf.abs(tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  3],
       [15,  3]], dtype=int32)>

In [46]:
tf.reduce_mean(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=-4>

In [47]:
tensor = tf.cast(tensor,dtype=tf.float16)

In [48]:
tf.reduce_mean(tensor)

<tf.Tensor: shape=(), dtype=float16, numpy=-4.75>

### Positional minimum or maximum

In [55]:
tensor = tf.constant([12,124,14,412, 12,4,56,43])

In [56]:
tf.math.argmin(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=5>

### Squeezing a tensor -> removing all 1-dim axes

In [62]:
tensor = tf.constant(tf.random.uniform(shape=[50]),shape=(1,5,1,10))
tensor

<tf.Tensor: shape=(1, 5, 1, 10), dtype=float32, numpy=
array([[[[0.0065074 , 0.43722284, 0.3366778 , 0.81566167, 0.19006848,
          0.6187165 , 0.40889525, 0.40879261, 0.50254333, 0.13833857]],

        [[0.35483348, 0.6674919 , 0.02145183, 0.45437884, 0.7692622 ,
          0.9595429 , 0.9896803 , 0.7042786 , 0.7327888 , 0.06955242]],

        [[0.80075514, 0.14861691, 0.41539037, 0.23958933, 0.96051276,
          0.46477652, 0.7922498 , 0.22696912, 0.6203611 , 0.8844104 ]],

        [[0.73478043, 0.12664056, 0.10713053, 0.3231542 , 0.7134541 ,
          0.9595643 , 0.7583536 , 0.43035924, 0.13512409, 0.26526642]],

        [[0.09686446, 0.35506678, 0.09240031, 0.03529966, 0.33262873,
          0.8262688 , 0.17436016, 0.3808856 , 0.5488844 , 0.25256824]]]],
      dtype=float32)>

In [63]:
tf.squeeze(tensor)

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.0065074 , 0.43722284, 0.3366778 , 0.81566167, 0.19006848,
        0.6187165 , 0.40889525, 0.40879261, 0.50254333, 0.13833857],
       [0.35483348, 0.6674919 , 0.02145183, 0.45437884, 0.7692622 ,
        0.9595429 , 0.9896803 , 0.7042786 , 0.7327888 , 0.06955242],
       [0.80075514, 0.14861691, 0.41539037, 0.23958933, 0.96051276,
        0.46477652, 0.7922498 , 0.22696912, 0.6203611 , 0.8844104 ],
       [0.73478043, 0.12664056, 0.10713053, 0.3231542 , 0.7134541 ,
        0.9595643 , 0.7583536 , 0.43035924, 0.13512409, 0.26526642],
       [0.09686446, 0.35506678, 0.09240031, 0.03529966, 0.33262873,
        0.8262688 , 0.17436016, 0.3808856 , 0.5488844 , 0.25256824]],
      dtype=float32)>

### One Hot Encoding

In [73]:
some_list = [[0,1],[2,3]]
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(2, 2, 4), dtype=float32, numpy=
array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.]],

       [[0., 0., 1., 0.],
        [0., 0., 0., 1.]]], dtype=float32)>

### Getting access to GPU's

In [79]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

**Laufzeit ändern:** Unter Laufzeit -> Laufzeit ändern -> GPU auswählen

In [1]:
import tensorflow as tf

In [2]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
!nvidia-smi

Tue Oct 12 13:38:26 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.74       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8    27W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------